name: Bloat

on:
    pull_request:

permissions:
  pull-requests: write

jobs:
    cargo_bloat_esp32:
        name: Cargo Bloat trouble esp32 example
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Install Rust
              uses: actions-rs/toolchain@v1
              with:
                toolchain: stable
            - name: Install cargo-bloat
              run: cargo install cargo-bloat
            - name: Run cargo bloat
              run: |
                cd examples/esp32 &&\
                echo "Bloat report for ESP32 example" > bloat.txt &&\
                cargo bloat --release >> ./bloat.txt
            - name: Post results to PR
              uses: marocchino/sticky-pull-request-comment@v2
              with:
                hide_and_recreate: true
                hide_classify: "OUTDATED"
                header: ESP32 Bloat Report
                path: ./examples/esp32/bloat.txt
            