name: Docs

on:
  push:
    branches: [main]

env:
  BUILDER_THREADS: '1'

jobs:
  doc:
    runs-on: ubuntu-latest

    # This will ensure at most one doc build job is running at a time
    # If another job is already running, the new job will wait.
    # If another job is already waiting, it'll be canceled.
    # This means some commits will be skipped, but that's fine because
    # we only care that the latest gets built.
    concurrency: doc

    steps:
      - uses: actions/checkout@v2
      - name: Install docserver
        run: |
          wget -q -O /usr/local/bin/docserver-builder "https://github.com/embassy-rs/docserver/releases/download/v0.5/builder"
          chmod +x /usr/local/bin/docserver-builder

      - name: build
        run: |
          mv rust-toolchain-nightly.toml rust-toolchain.toml
          mkdir crates
          docserver-builder -i trouble-host -o crates/trouble-host/git.zup
          docserver-builder -i trouble-host-macros -o crates/trouble-host-macros/git.zup

      - name: upload
        run: |
          mkdir -p ~/.kube
          echo "${{secrets.KUBECONFIG}}" > ~/.kube/config
          POD=$(kubectl -n embassy get po -l app=docserver -o jsonpath={.items[0].metadata.name})
          kubectl cp crates $POD:/data
